---
- name: Setup WebServer
  hosts: websrvgrp
  become: yes
  tasks:
    - name: Install apache2 in centos8
      yum:
        name: httpd
        state: present
    - name: Start & Enable apache2
      service:
        name: httpd
        state: started
        enabled: yes
